# Generated by Django 2.2.6 on 2019-12-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('strMeal', models.CharField(max_length=100)),
                ('idMeal', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
