# Generated by Django 2.2.7 on 2019-12-14 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meals',
        ),
    ]
